# Site settings
title: Luke Rohm
email: lukerohm1@gmail.com
description: Awesome Nuff Said
baseurl: ""
url: "www.lukerohm.com"
twitter_username: lukerohm
avatar: "https://pbs.twimg.com/profile_images/378800000107218810/7a0567deef3a3b24108194d26e655d8a.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "My Author" # Set default author name
      categories: "cats"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
